(() => {
  'use strict';
  const $=id=>document.getElementById(id);
  const KEY='aiku.stream.v3';
  const defaults={library:[],history:[],continue:[],repos:[],providers:[],settings:{autoplay:true,bridgeUrl:'',searchParallel:true}};
  let db=load(), page='home', searchResults=[];
  function load(){try{
    const raw=JSON.parse(localStorage.getItem(KEY)||'{}')||{};
    const out={...defaults,...raw,settings:{...defaults.settings,...(raw.settings||{})}};
    out.library=Array.isArray(out.library)?out.library:[];
    out.history=Array.isArray(out.history)?out.history:[];
    out.continue=Array.isArray(out.continue)?out.continue:[];
    out.repos=Array.isArray(out.repos)?out.repos:[];
    out.providers=Array.isArray(out.providers)?out.providers:[];
    return deep(out);
  }catch{return deep(defaults)}}
  function deep(x){return JSON.parse(JSON.stringify(x))}
  function save(){localStorage.setItem(KEY,JSON.stringify(db))}
  function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function uid(){return crypto.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2)}
  function toast(s){let e=document.querySelector('.toast2');if(!e){e=document.createElement('div');e.className='toast2';document.body.appendChild(e)}e.textContent=s;e.classList.add('show');clearTimeout(e.t);e.t=setTimeout(()=>e.classList.remove('show'),2400)}
  function norm(raw){try{let u=String(raw||'').trim();if(!/^https?:\/\//i.test(u))u='https://'+u;let x=new URL(u);return /^https?:$/.test(x.protocol)?x.toString():null}catch{return null}}
  function baseOf(u){try{let x=new URL(u);return x.origin+x.pathname.replace(/\/[^\/]*$/,'/')}catch{return u}}
  function abs(u,base){try{return new URL(u,base).toString()}catch{return u}}
  function go(p){page=p;render();scrollTo(0,0)}
  function nav(){document.querySelectorAll('#topnav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page))}
  function tile(x,kind='library'){
    let title=x.title||x.name||'Untitled', img=x.poster||x.thumbnail||'';
    let prog=x.duration&&x.position?Math.min(100,x.position/x.duration*100):0;
    return `<article class="tile" data-open="${esc(x.url||'')}" data-id="${esc(x.id||'')}"><div class="tile-img">${img?`<img loading="lazy" src="${esc(img)}" onerror="this.parentNode.innerHTML='▶'">`:'▶'}</div>${prog?`<div class="progress-mini"><i style="width:${prog}%"></i></div>`:''}<div class="tile-body"><div class="tile-title">${esc(title)}</div><div class="tile-sub">${esc(x.provider||kind)}</div></div></article>`
  }
  function empty(t){return `<div class="empty">${esc(t)}</div>`}
  function home(){
    let c=db.continue.slice(0,12), l=db.library.slice(0,12), h=db.history.slice(0,12), p=db.providers.filter(x=>x.enabled!==false).slice(0,10);
    return `<div class="hub-hero"><div class="eyebrow">CLOUDSTREAM-STYLE WEB HOST</div><h1>One player. Your providers.</h1><p>Paste a CloudStream repository, discover its manifest and plugin list, keep your collection locally, and route executable providers through a compatible runtime.</p><div class="hub-actions"><button class="btn" id="addRepo">＋ Add CloudStream repo</button><button class="btn ghost" id="globalSearchFocus">Search providers</button><button class="btn ghost" id="addUrl">＋ Add media URL</button></div></div><section><div class="section-title"><h2>Enabled providers</h2><button class="btn ghost" data-go="extensions">Manage</button></div>${p.length?`<div class="provider-strip">${p.map(providerChip).join('')}</div>`:empty('Add a CloudStream repository to discover providers.')}</section><section><div class="section-title"><h2>Continue watching</h2></div>${c.length?`<div class="grid">${c.map(x=>tile(x,'continue')).join('')}</div>`:empty('Nothing in progress yet.')}</section><section><div class="section-title"><h2>My collection</h2><button class="btn ghost" data-go="library">View all</button></div>${l.length?`<div class="grid">${l.map(x=>tile(x)).join('')}</div>`:empty('Your collection is stored locally in this browser.')}</section><section><div class="section-title"><h2>Recently watched</h2></div>${h.length?`<div class="grid">${h.map(x=>tile(x,'history')).join('')}</div>`:empty('No playback history.')}</section>`
  }
  function providerChip(p){return `<button class="provider-chip" data-provider-search="${esc(p.id||p.internalName||p.name)}"><img src="${esc(p.iconUrl||'')}" onerror="this.style.display='none'"><span>${esc(p.name||p.internalName)}</span></button>`}
  function library(){return `<div class="hub"><div class="section-title"><h2>My List</h2><button class="btn" id="addUrl">＋ Add URL</button></div>${db.library.length?`<div class="grid">${db.library.map(tile).join('')}</div>`:empty('Your collection is empty.')}</div>`}
  function history(){return `<div class="hub"><div class="section-title"><h2>History</h2><button class="btn ghost danger" id="clearHistory">Clear history</button></div>${db.history.length?`<div class="grid">${db.history.map(x=>tile(x,'history')).join('')}</div>`:empty('No playback history.')}</div>`}
  function extensions(){
    let repos=db.repos||[], providers=db.providers||[];
    return `<div class="hub"><div class="section-title"><h2>Extensions</h2><button class="btn" id="addRepo">＋ Add repository</button></div><div class="bridge-panel"><div><span class="eyebrow">RUNTIME</span><h3>CloudStream compatibility bridge</h3><p>A browser cannot execute Android/Kotlin <code>.cs3</code> bytecode itself. AikuStream therefore separates repository discovery from execution. Point this host at a compatible CloudStream runtime/bridge to make installed .cs3 providers executable.</p></div><div class="bridge-row"><input id="bridgeUrl" value="${esc(db.settings.bridgeUrl||'')}" placeholder="https://your-bridge.example/api"><button class="btn" id="saveBridge">Save runtime</button><button class="btn ghost" id="testBridge">Test</button></div><small class="muted">Expected bridge operations: <code>GET /health</code>, <code>POST /repo</code>, <code>POST /search</code>, <code>POST /load</code>, <code>POST /links</code>.</small></div><div class="section-title"><h2>Repositories <span class="count">${repos.length}</span></h2></div>${repos.length?`<div class="list">${repos.map((r,i)=>repoCard(r,i)).join('')}</div>`:empty('Paste any public CloudStream repo.json or plugins.json URL.') }<div class="section-title"><h2>Discovered providers <span class="count">${providers.length}</span></h2><button class="btn ghost" id="refreshAll">Refresh all</button></div>${providers.length?`<div class="provider-list">${providers.map((p,i)=>providerCard(p,i)).join('')}</div>`:empty('No providers discovered yet.')}</div>`
  }
  function repoCard(r,i){return `<div class="repo-card"><div class="repo-head">${r.iconUrl?`<img src="${esc(r.iconUrl)}">`:''}<div class="grow"><b>${esc(r.name||r.url)}</b><small>${esc(r.description||'')}</small><small>${r.plugins?.length||0} providers · ${r.refreshed?new Date(r.refreshed).toLocaleString():'not refreshed'}</small></div></div><small class="mono">${esc(r.url)}</small><div class="repo-actions"><button class="btn" data-refresh-repo="${i}">Refresh</button><button class="btn ghost" data-install-all="${i}">Enable all</button><button class="btn ghost danger" data-remove-repo="${i}">Remove</button></div></div>`}
  function providerCard(p,i){let runnable=p.runnable?'READY':'BRIDGE';return `<div class="provider-card"><div class="provider-icon">${p.iconUrl?`<img src="${esc(p.iconUrl)}">`:'🧩'}</div><div class="grow"><b>${esc(p.name||p.internalName)}</b><small>${esc((p.authors||[]).join(', '))} · v${esc(p.version||'?')} · ${esc((p.tvTypes||[]).join(', '))}</small><small>${esc(p.description||'')}</small></div><span class="status ${p.enabled!==false?'on':''}">${p.enabled!==false?runnable:'OFF'}</span><button class="btn ghost" data-toggle-provider="${i}">${p.enabled!==false?'Disable':'Enable'}</button></div>`}
  function settings(){return `<div class="hub"><div class="section-title"><h2>Settings & data</h2></div><div class="panel"><div class="switch"><div><b>Autoplay</b><small class="muted">Start compatible media automatically</small></div><input id="autoplay" type="checkbox" ${db.settings.autoplay?'checked':''}></div><div class="switch"><div><b>Parallel provider search</b><small class="muted">Search enabled providers concurrently through the bridge</small></div><input id="searchParallel" type="checkbox" ${db.settings.searchParallel?'checked':''}></div><div class="hub-actions"><button class="btn" id="exportData">Export data</button><button class="btn ghost" id="importData">Import data</button><button class="btn ghost danger" id="wipeData">Erase local data</button></div></div></div>`}
  function render(){
    let h=$('hub');
    if(!h)return;
    try{
      const hasVideo=new URLSearchParams(location.search).has('url');
      if(hasVideo){
        $('open')?.classList.add('hidden');
        $('view')?.classList.remove('hidden');
        document.body.classList.add('player-mode');
        return;
      }
      $('open')?.classList.remove('hidden');
      $('view')?.classList.add('hidden');
      document.body.classList.remove('player-mode');
      nav();
      h.innerHTML=page==='home'?home():page==='library'?library():page==='history'?history():page==='extensions'?extensions():settings();
      bind();
      document.body.classList.add('aiku-hub-ready');
    }catch(e){
      console.error('AikuStream UI error',e);
      $('open')?.classList.remove('hidden');
      h.innerHTML='<div class="hub"><div class="empty"><b>AikuStream UI failed to render.</b><br><small>'+esc(e?.message||'Unknown error')+'</small><br><button class="btn" id="recoverUi" style="margin-top:12px">Reset local app data</button></div></div>';
      $('recoverUi')?.addEventListener('click',()=>{localStorage.removeItem(KEY);location.reload()});
    }
  }
  function bind(){
    document.querySelectorAll('#topnav button').forEach(b=>b.onclick=()=>go(b.dataset.page));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));document.querySelectorAll('[data-open]').forEach(e=>e.onclick=()=>openItem(e.dataset.open,e.dataset.id));
    $('addUrl')?.addEventListener('click',urlModal);$('directUrlFab')?.addEventListener('click',urlModal);$('addRepo')?.addEventListener('click',repoModal);$('clearHistory')?.addEventListener('click',()=>{if(confirm('Clear playback history?')){db.history=[];db.continue=[];save();render()}});
    $('exportData')?.addEventListener('click',exportData);$('importData')?.addEventListener('click',importData);$('wipeData')?.addEventListener('click',()=>{if(confirm('Erase all AikuStream local data?')){localStorage.removeItem(KEY);db=load();render();toast('Local data erased')}});
    $('autoplay')?.addEventListener('change',e=>{db.settings.autoplay=e.target.checked;save()});$('searchParallel')?.addEventListener('change',e=>{db.settings.searchParallel=e.target.checked;save()});
    $('globalSearchFocus')?.addEventListener('click',searchModal);$('saveBridge')?.addEventListener('click',()=>{db.settings.bridgeUrl=norm($('bridgeUrl').value)||'';save();toast(db.settings.bridgeUrl?'Runtime saved':'Runtime cleared')});$('testBridge')?.addEventListener('click',testBridge);$('refreshAll')?.addEventListener('click',refreshAll);
    document.querySelectorAll('[data-refresh-repo]').forEach(b=>b.onclick=()=>refreshRepo(+b.dataset.refreshRepo));document.querySelectorAll('[data-remove-repo]').forEach(b=>b.onclick=()=>removeRepo(+b.dataset.removeRepo));document.querySelectorAll('[data-install-all]').forEach(b=>b.onclick=()=>toggleRepo(+b.dataset.installAll,true));document.querySelectorAll('[data-toggle-provider]').forEach(b=>b.onclick=()=>{let p=db.providers[+b.dataset.toggleProvider];p.enabled=p.enabled===false;save();render()});document.querySelectorAll('[data-provider-search]').forEach(b=>b.onclick=()=>providerSearch(b.dataset.providerSearch));
  }
  function urlModal(){modal(`<h2>Add media</h2><p>Direct MP4/WebM/MOV/HLS links work immediately. Other containers can use the Aiku browser converter.</p><input id="mUrl" placeholder="https://example.com/video.m3u8"><input id="mTitle" placeholder="Title (optional)" style="margin-top:8px"><input id="mPoster" placeholder="Poster URL (optional)" style="margin-top:8px"><div class="modal-actions"><button class="btn ghost" data-close>Cancel</button><button class="btn" id="mPlay">Save & play</button></div>`);$('mPlay').onclick=()=>{let url=norm($('mUrl').value);if(!url)return toast('Enter a valid URL');let x={id:uid(),url,title:$('mTitle').value.trim()||name(url),poster:$('mPoster').value.trim(),added:Date.now(),position:0,duration:0};if(!db.library.some(i=>i.url===url))db.library.unshift(x);save();closeModal();openItem(url,x.id)}}
  function repoModal(){modal(`<h2>Add CloudStream repository</h2><p>Paste <code>repo.json</code>, <code>plugins.json</code>, or a raw JSON URL. AikuStream resolves <code>pluginLists</code> recursively.</p><input id="repoUrl" placeholder="https://raw.githubusercontent.com/.../repo.json"><div class="modal-actions"><button class="btn ghost" data-close>Cancel</button><button class="btn" id="repoInstall">Discover providers</button></div>`);$('repoInstall').onclick=()=>{let u=norm($('repoUrl').value);if(!u)return toast('Enter a valid URL');closeModal();installRepo(u)}}
  function modal(body){let e=document.createElement('div');e.className='modal-back';e.innerHTML=`<div class="modal">${body}</div>`;e.onclick=x=>{if(x.target===e||x.target.matches('[data-close]'))e.remove()};document.body.appendChild(e)}function closeModal(){document.querySelector('.modal-back')?.remove()}
  async function getJson(url){let r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);return await r.json()}
  async function readRepo(url){let j=await getJson(url);let repo={url,name:j.name||j.title||'CloudStream repository',description:j.description||'',iconUrl:j.iconUrl||'',manifestVersion:j.manifestVersion||null,pluginLists:[],plugins:[]};if(Array.isArray(j))repo.plugins=j;else if(Array.isArray(j.plugins))repo.plugins=j.plugins;else if(Array.isArray(j.extensions))repo.plugins=j.extensions;for(let u of (j.pluginLists||[]))repo.pluginLists.push(abs(u,baseOf(url)));if(!repo.plugins.length&&repo.pluginLists.length){for(let u of repo.pluginLists){try{let x=await getJson(u);if(Array.isArray(x))repo.plugins.push(...x);else if(Array.isArray(x.plugins))repo.plugins.push(...x.plugins);else if(Array.isArray(x.extensions))repo.plugins.push(...x.extensions)}catch(e){repo.errors=(repo.errors||[]).concat(u+': '+e.message)}}}repo.plugins=repo.plugins.map(p=>({...p,url:p.url?abs(p.url,url):p.url,repoUrl:url,enabled:p.enabled!==false,runnable:!String(p.url||'').toLowerCase().includes('.cs3')}));repo.refreshed=Date.now();return repo}
  async function installRepo(url){toast('Discovering repository…');try{let repo=await readRepo(url), idx=db.repos.findIndex(x=>x.url===url);if(idx>=0)db.repos[idx]=repo;else db.repos.push(repo);mergeProviders(repo);save();toast(`Found ${repo.plugins.length} provider(s)`);go('extensions')}catch(e){toast('Repository failed: '+e.message)}}
  async function refreshRepo(i){let old=db.repos[i];if(!old)return;toast('Refreshing '+(old.name||'repository')+'…');try{let repo=await readRepo(old.url);db.repos[i]=repo;mergeProviders(repo);save();render();toast(`Refreshed ${repo.plugins.length} provider(s)`)}catch(e){toast('Refresh failed: '+e.message)}}
  function mergeProviders(repo){for(let p of repo.plugins||[]){let id=p.internalName||p.name||p.url;let k=db.providers.findIndex(x=>(x.internalName||x.name||x.url)===id);let next={...p,id,enabled:k>=0?db.providers[k].enabled:true,repoName:repo.name,repoUrl:repo.url};if(k>=0)db.providers[k]={...db.providers[k],...next};else db.providers.push(next)}}
  function removeRepo(i){let r=db.repos[i];if(!r)return;db.repos.splice(i,1);db.providers=db.providers.filter(p=>p.repoUrl!==r.url);save();render()}
  function toggleRepo(i,on){let r=db.repos[i];for(let p of db.providers)if(p.repoUrl===r.url)p.enabled=on;save();render()}
  async function refreshAll(){for(let i=0;i<db.repos.length;i++)try{db.repos[i]=await readRepo(db.repos[i].url);mergeProviders(db.repos[i])}catch{}save();render();toast('All repositories refreshed')}
  async function testBridge(){let u=norm($('bridgeUrl')?.value||db.settings.bridgeUrl);if(!u)return toast('Enter a bridge URL first');try{let r=await fetch(u.replace(/\/$/,'')+'/health',{headers:{accept:'application/json'}});if(!r.ok)throw Error('HTTP '+r.status);let j=await r.json().catch(()=>({}));toast('Bridge online'+(j.version?' · '+j.version:''))}catch(e){toast('Bridge test failed: '+e.message)}}
  async function bridge(path,body){let b=norm(db.settings.bridgeUrl);if(!b)throw Error('No CloudStream runtime configured');let r=await fetch(b.replace(/\/$/,'')+path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw Error('Bridge HTTP '+r.status);return r.json()}
  function searchModal(){modal(`<h2>Search providers</h2><input id="providerQuery" placeholder="Movie, anime, series…"><div class="modal-actions"><button class="btn ghost" data-close>Cancel</button><button class="btn" id="providerSearchBtn">Search</button></div><div id="providerResults" class="search-results"></div>`);$('providerQuery').focus();$('providerQuery').onkeydown=e=>{if(e.key==='Enter')runProviderSearch()};$('providerSearchBtn').onclick=runProviderSearch}
  async function providerSearch(id){let p=db.providers.find(x=>(x.id||x.internalName||x.name)===id);searchModal();$('providerQuery').value='';$('providerQuery').placeholder='Search '+(p?.name||'provider');$('providerSearchBtn').onclick=()=>runProviderSearch(id)}
  async function runProviderSearch(forceId){let q=($('providerQuery')?.value||'').trim();if(!q)return toast('Enter a search query');let providers=db.providers.filter(p=>p.enabled!==false&&(!forceId||(p.id||p.internalName||p.name)===forceId));if(!providers.length)return toast('No enabled providers');$('providerResults').innerHTML='<div class="muted">Searching…</div>';try{let out=await bridge('/search',{query:q,providers:providers.map(p=>({id:p.id,internalName:p.internalName,name:p.name,url:p.url,repoUrl:p.repoUrl}))});searchResults=out.results||[];$('providerResults').innerHTML=searchResults.length?searchResults.map((x,i)=>`<div class="search-row"><img src="${esc(x.poster||x.thumbnail||'')}" onerror="this.style.display='none'"><div class="grow"><b>${esc(x.title||x.name)}</b><small>${esc(x.provider||'')}</small></div><button class="btn" data-result="${i}">Open</button></div>`).join(''):empty('No results');document.querySelectorAll('[data-result]').forEach(b=>b.onclick=()=>openBridgeResult(searchResults[+b.dataset.result]))}catch(e){$('providerResults').innerHTML=`<div class="empty">${esc(e.message)}<br><small>Configure a compatible CloudStream runtime in Extensions.</small></div>`}}
  async function openBridgeResult(item){if(!item)return;try{let detail=await bridge('/load',{item});showDetail(detail)}catch(e){toast('Load failed: '+e.message)}}
  function showDetail(x){modal(`<div class="detail"><img src="${esc(x.poster||x.thumbnail||'')}" onerror="this.style.display='none'"><div class="grow"><h2>${esc(x.title||x.name||'Title')}</h2><p>${esc(x.description||x.overview||'')}</p><div class="hub-actions"><button class="btn" id="loadLinksBtn">Find sources</button><button class="btn ghost" id="detailSave">＋ My List</button></div></div></div><div id="episodeArea"></div>`);$('detailSave').onclick=()=>{let item={id:x.id||uid(),url:x.url||x.id,title:x.title||x.name,poster:x.poster||x.thumbnail,provider:x.provider};if(!db.library.some(i=>i.id===item.id))db.library.unshift(item);save();toast('Added to My List')};$('loadLinksBtn').onclick=()=>loadLinks(x)}
  async function loadLinks(item){let a=$('episodeArea');a.innerHTML='<div class="muted">Finding sources…</div>';try{let r=await bridge('/links',{item});let links=r.links||r.sources||[];a.innerHTML=links.length?`<div class="source-list">${links.map((s,i)=>`<button class="source-btn" data-source="${i}"><b>${esc(s.name||s.server||'Source '+(i+1))}</b><small>${esc(s.quality||s.type||'Auto')}</small></button>`).join('')}</div>`:empty('No playable sources returned.');document.querySelectorAll('[data-source]').forEach(b=>b.onclick=()=>{let s=links[+b.dataset.source];if(s?.url){closeModal();openItem(s.url)}})}catch(e){a.innerHTML=empty(e.message)}}
  function openItem(url,id){if(!url)return;let x=db.library.find(i=>i.id===id)||db.library.find(i=>i.url===url);location.href='?url='+encodeURIComponent(url)+'&title='+encodeURIComponent(x?.title||name(url))+(x?.poster?'&poster='+encodeURIComponent(x.poster):'')+(id?'&item='+encodeURIComponent(id):'')}
  function name(u){try{return decodeURIComponent(new URL(u).pathname.split('/').filter(Boolean).pop()||'Video').replace(/[-_]/g,' ')}catch{return'Video'}}
  function exportData(){let blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='aikustream-library-v3.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
  function importData(){let i=document.createElement('input');i.type='file';i.accept='.json,application/json';i.onchange=async()=>{try{let x=JSON.parse(await i.files[0].text());db={...defaults,...x,settings:{...defaults.settings,...(x.settings||{})}};save();render();toast('Library imported')}catch{toast('Invalid AikuStream data')}};i.click()}
  if(!new URLSearchParams(location.search).has('url')) render();
})();
